# -*- coding: utf-8 -*-
"""DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2WCJ25zv5f9PU0nnUGBgmne6bFriwrV

Doubly Linked List
A doubly-linked list is quite similar to a "singly-linked" list. Just need to add a prev pointer to all the nodes.
"""

class Node:
    def __init__(self, val =None):
        self.val = val
        self.next = None
        self.prev =None

"""

Push
The push operation is also the same mostly. The new node only needs to be linked to the second-to-last node.ed as code
```

"""

class Doubly_node:
    def __init__(self):
        self.head = None
    def push(self, val):
        """Insert at the end"""
        new_node = Node(val)
        if self.head is None:
            self.head = new_node
            return
        last = self.head
        while last.next is not None:
            last = last.next
        last.next = new_node
        new_node.prev = last



def pop(self):
        """Remove from the end"""
        if self.head is None:
            raise Exception("Cannot pop. No value.")
        if self.head.next is None:
            val = self.head.val
            self.head = None
            return val
        temp = self.head
        while temp.next is not None:
            prev = temp
            temp = temp.next
        val = temp.val
        prev.next = None
        return val

def __str__(self):
        ret_str = '['
        temp = self.head
        while temp is not None:
            ret_str += str(temp.val) + ', '
            temp = temp.next
        ret_str = ret_str.rstrip(', ')
        ret_str += ']'
        return ret_str

l = Doubly()
l.push(1)
l.push(2)
l.push(3)
print(l)
def insert(self, index, val):
  new_node=Node(val)
  #insertion at index e is different
  if index == 6:
    new_node.next = self.head
    self.head.prev = new_node
    self.head =new_node
    return
  #for other indices
  self.head= temp
  counter = 0
  while temp is not None and counter < index:
    prev = temp
    temp =temp.next
    counter += 1
    #print(counter)

